config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :users
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "products#index"
  resource :basket, only: %i(show)
  resource :charge, only: %i(create)
  resource :favorite, only: %i(show)
  resources :products, only: %i(show) do 
    resource :favorites, only: %i(create destroy)
    scope module: :products do
      resources :add_to_baskets, only: %i(create)
      resources :delete_in_baskets, only: %i(create)
    end
  end 
 
  
  namespace :admins do
    root to: "dashboards#index"
    resources :products, only: %i(new create)
    resource :sales_record, only: %i(show)
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :purchase_record_products, through: :products

  def total_sales
     sold_products = self.products.joins(:purchase_record_products)
     PriceCalculator.total(sold_products)
  end

  def this_month_sales
    sold_products = self.products
    .joins(:purchase_record_products)
    .where({ purchase_record_products: {created_at: Time.current.all_month} })
     PriceCalculator.total(sold_products)
  end

  def today_sales
    sold_products = self.products
    .joins(:purchase_record_products)
    .where({ purchase_record_products: {created_at: Time.current.all_day} })
     PriceCalculator.total(sold_products)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :basket_products, dependent: :destroy
  has_many :products, through: :basket_products

  def total_price(product_ids: nil)
    products = product_ids ? self.products.where(id: product_ids) : self.products
    PriceCalculator.total(products)
  end

end

app/models/basket_product.rb
class BasketProduct < ApplicationRecord
  belongs_to :basket
  belongs_to :product
end

app/models/charge.rb
class Charge 
  def initialize
     Stripe.api_key = ENV['STRIPE_SECRET_KEY']
  end

  def create!(price, token)
    Stripe::Charge.create({
      amount: price,
      currency: 'jpy',
      description: 'Example charge',
      source: token
    })
    end

    def self.create!(price, token)
      charge = self.new
      charge.create!(price, token)
    end
end

app/models/concerns/price_calculator.rb
module PriceCalculator
 def self.total(products)
  products.sum(:price)
 end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/product.rb
class Product < ApplicationRecord
  include Hashid::Rails
  mount_uploader :image, ImageUploader
  has_many :basket_products, dependent: :destroy
  has_many :purchase_record_products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  belongs_to :admin
  
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image, presence: true
end

app/models/purchase_record.rb
class PurchaseRecord < ApplicationRecord
  belongs_to :user
  has_many :purchase_record_products, dependent: :destroy
  has_many :products, through: :purchase_record_products

end

app/models/purchase_record_product.rb
class PurchaseRecordProduct < ApplicationRecord
  belongs_to :product 
  belongs_to :purchase_record
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  
  has_one :basket, dependent: :destroy
  has_one :purchase_record, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_products, through: :favorites, source: :product
  
  
 

  def prepare_basket
    basket || create_basket
  end

 def prepare_purchase_record
   purchase_record || create_purchase_record
 end

def already_favorited?(product)
  self.favorites.exists?(product_id: product.id)
end


  def checkout!(token, product_ids:)
    total = basket.total_price(product_ids: product_ids)
    
    transaction do
      basket_products = basket.basket_products.where(product_id: product_ids)
      basket_products.each(&:destroy!)

      purchase_record = prepare_purchase_record
      ids = product_ids.map { |id| { product_id: id } }
      purchase_record.purchase_record_products.create!(ids)
    end

    Charge.create!(total, token)
  end

end

app/controllers/admins/application_controller.rb
class Admins::ApplicationController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admins/dashboards_controller.rb
class Admins::DashboardsController < Admins::ApplicationController
  def index
  end
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < Admins::ApplicationController
  
  def new 
    @product = current_admin.products.build
  end

  def create 
    @product = current_admin.products.build(product_params)
    if @product.save
      redirect_to admins_root_path, success: '商品を追加しました。'
    else
      flash[:error] = '追加に失敗しました。'
      render :new
    end
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

app/controllers/admins/sales_records_controller.rb
class Admins::SalesRecordsController < Admins::ApplicationController
  def show
    @purchase_record_products = current_admin.purchase_record_products.preload(:product)
    if params[:start_at] && params[:end_at]
        start_at = DateTime.parse(params[:start_at])
        end_at = DateTime.parse(params[:end_at])
        @purchase_record_products = @purchase_record_products.where(created_at: start_at..end_at)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      root_path
    else resource.is_a?(Admin)
      admins_root_path
    end
  end
  

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :authenticate_user!

  def show 
    basket = current_user.prepare_basket
    @products = basket.products
    @total_price = basket.products.sum(:price)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
     Stripe.api_key = ENV['STRIPE_SECRET_KEY']
   
    token = params[:stripeToken]
    product_ids = params[:product_ids].map(&:to_i)
    current_user.checkout!(token, product_ids: product_ids)
    redirect_to root_path, success: '決済に成功しました。'
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  
  def show 
   @favorite = current_user.favorite_products
  end

  def create 
   @product = Product.find(params[:product_id])
   @favorite = current_user.favorites.create(product_id: @product.id)
   redirect_back(fallback_location: root_path)
   
  end

  def destroy
    @product = Product.find(params[:product_id])
    @favorite = current_user.favorites.find_by(product_id: @product.id)
    @favorite.destroy
     redirect_back(fallback_location: root_path)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page])
  end

   def show 
    @product = Product.find(params[:id])
   end
  
    
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/baskets/show.html.erb
<h1 class="mb-4">Shopping Basket</h1>

  <% @products.each do |product| %>
    <div class="row border-bottom">
      
        <div class="col-md-4 my-2">
          <%= image_tag product.image.url, :width => '180px', :height => 'auto' %>
        </div>
        <div class="col-md-2">
          <p class="h2 mt-4"><%= product.name %></p>
        </div>  
        <div class="col-md-2">
          <p class="h2 mt-4"><%= product.price %> 円</p>
        </div>
        <div class="col-md-2  mt-4">
          <%= link_to product_delete_in_baskets_path(product), method: :post do %>
           <i class="fas fa-2x fa-trash-alt"></i>
          <% end %>
        </div>
      </div>
  <% end %>


<div class="fix ">
  <div class="bg-light p-2 rounded">
    <%= form_tag charge_path do %>
      <% @products.each do |p| %>
        <%= hidden_field_tag 'product_ids[]', p.id %>
      <% end %>
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key=<%= ENV['STRIPE_API_KEY'] %>
              data-description="商品のご購入"
              data-amount=<%= @total_price %>
              data-locale="auto"
              data-currency="jpy">
      </script>
    <% end %>
    <p class="pt-2">ご注文小計 :  <span class="text-danger h4"><%= @total_price %> 円</span></p>
  </div>

   <%= link_to root_path do %>
      <p class="btn btn-dark mt-3 w-100">買い物を続ける</p>
   <% end %>
</div>


app/views/favorites/show.html.erb
<h1 class="mb-4">Your favorite item</h1>
  <% if @favorite.empty? %>
   <p class="h3">お気に入りに追加した商品はありません。</p>
  <% end %>

  <% current_user.favorite_products.each do |product| %>
    <div class="row border-bottom">
      
        <div class="col-md-4 my-2">  
          <%= image_tag product.image.url, :width => '180px', :height => 'auto' %>
        </div>
        <div class="col-md-2">
          <p class="h2 mt-4"><%= product.name %></p>
        </div>
        <div class="col-md-2">
          <p class="h2 mt-4"><%= product.price %> 円</p>
        </div>
        <div class="col-md-2  mt-4">
          <% if current_user.already_favorited?(product) %>
              <%= link_to  product_favorites_path(product), method: :delete do %>
                <i class="fas fa-2x fa-heart red_heart"></i>
              <% end %>
          <% else %>
              <%= link_to product_favorites_path(product), method: :post do %>
                <i class="far fa-2x fa-heart red_heart"></i>
              <% end %>
          <% end %>
        </div>
       <div class="col-md-2 mt-4">
          <%= link_to product_path(product) do %>
            <p class="btn btn-primary">商品詳細</p>
          <% end %>
       </div>
    
    </div>
  <% end %>

  <div class="fix">
    <%= link_to root_path do %>
        <p class="btn btn-dark mt-3">Back Home</p>
    <% end %>
  </div>
