config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :users
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "products#index"
  resource :basket, only: %i(show)
  resource :charge, only: %i(create)
  resource :favorite, only: %i(show)
  resources :products, only: %i(show) do 
    resource :favorites, only: %i(create destroy)
    scope module: :products do
      resources :add_to_baskets, only: %i(create)
      resources :delete_in_baskets, only: %i(create)
    end
  end 
 
  
  namespace :admins do
    root to: "dashboards#index"
    resources :products, only: %i(new create)
    resource :sales_record, only: %i(show)
  end

end

app/models/product.rb
class Product < ApplicationRecord
  include Hashid::Rails
  mount_uploader :image, ImageUploader
  has_many :basket_products, dependent: :destroy
  has_many :purchase_record_products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  belongs_to :admin
  
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image, presence: true
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < Admins::ApplicationController
  
  def new 
    @product = current_admin.products.build
  end

  def create 
    @product = current_admin.products.build(product_params)
    if @product.save
      redirect_to admins_root_path, success: '商品を追加しました。'
    else
      flash[:error] = '追加に失敗しました。'
      render :new
    end
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

app/controllers/products/add_to_baskets_controller.rb
class Products::AddToBasketsController < Products::ApplicationController
  def create
  basket = current_user.prepare_basket
  product = Product.find(params[:product_id])
  basket.basket_products.create!(product_id: product.id)
  redirect_to basket_path
  end
end

app/controllers/products/application_controller.rb
class Products::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/products/delete_in_baskets_controller.rb
class Products::DeleteInBasketsController < Products::ApplicationController
  def create
    basket = current_user.prepare_basket
    product = Product.find(params[:product_id])
    
    basket_product = basket.basket_products.find_by(product_id: product.id)
    basket_product.destroy!
    
    redirect_to basket_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page])
  end

   def show 
    @product = Product.find(params[:id])
   end
  
    
  end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>
  
<h1 class="mb-4">All items</h1>
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="bg-light p-2 mt-2">
        <div class="appeal">
          <%= link_to product_path(product) do %>
              <%= image_tag product.image.url, :width => '90%', :height => 'auto' %>
            <div class="mask">
              <div class="caption">Click it and see the item details.</div>
            </div>
          <% end %>
      </div>
        <p class="h4 pl-3"><%= product.name %></p>
        <p class="h5 pl-3"><%= product.price.to_s(:delimited) %>円</p>
      </div>
    </div>
  <% end %>
 </div>

 <%= paginate @products %>
 

app/views/products/new.html.erb
<div class="border p-5 m-4"> 
  <div class="pb-4">
    <h1>Product New</h1>
  </div>
  <%= form_for(@product, url:{controller:'products', action: 'create'}) do |f| %>
    <div class="form-group">
      <label for="name">Name</label>
      <%= f.text_field :name, class:"form-control" %>
    </div>

    <div class="form-group">
    <label for="description">Description</label>
    <%= f.text_area :description, {row:3, class:"form-control"} %>
    </div>
    
    <div class="form-group">
    <label for="price">Price</label>
    <%= f.text_field :price, class:"form-control" %>
    </div>

    <div class="form-group">
    <label for="image">Image</label>
    <%= f.file_field :image, accept:"image/jpg,image/jpeg,image/png", class:"form-control-file" %>
    </div>


    <%= f.submit "Add product", class:"btn btn-dark" %>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row mt-50">
  <div class="col-md-6"><%= image_tag @product.image.url, :width => '100%', :height => 'auto' %></div>
  <div class="col-md-4" id="product-show">
    <p class="h1"><%= @product.name %></p>
    <p class="h3"><%= @product.price %> 円</p>
    <p><%= @product.description %></p>

    <div class="row ">
      <div class="col-md-6">
        <%= link_to product_add_to_baskets_path(@product), method: :post do %>
          <div class="btn btn-primary">買い物かごに入れる</div>
        <% end %>
      
      </div>    
      <div class="col-md-4 "> 
        <% unless current_user.present? %>
        <%= link_to new_user_session_path do %>
            <i class="far fa-2x fa-heart red_heart"></i>
          <% end%>
        <% else %>

          <% if current_user.already_favorited?(@product) %>
            <%= link_to  product_favorites_path(@product), method: :delete do %>
              <i class="fas fa-2x fa-heart red_heart"></i>
              
            <% end %>
          <% else %>
            <%= link_to product_favorites_path(@product), method: :post do %>
              <i class="far fa-2x fa-heart red_heart"></i>
            <% end%>
          <% end%>
        <% end%>
      </div>
    </div>
  </div>
</div>

<div class="text-right">
  <%= link_to root_path do %>
      <p class="btn btn-dark mt-3">Back Home</p>
   <% end %>
</div>