config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  devise_for :users
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "products#index"
  resource :basket, only: %i(show)
  resource :charge, only: %i(create)
  resource :favorite, only: %i(show)
  resources :products, only: %i(show) do 
    resource :favorites, only: %i(create destroy)
    scope module: :products do
      resources :add_to_baskets, only: %i(create)
      resources :delete_in_baskets, only: %i(create)
    end
  end 
 
  
  namespace :admins do
    root to: "dashboards#index"
    resources :products, only: %i(new create)
    resource :sales_record, only: %i(show)
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :purchase_record_products, through: :products

  def total_sales
     sold_products = self.products.joins(:purchase_record_products)
     PriceCalculator.total(sold_products)
  end

  def this_month_sales
    sold_products = self.products
    .joins(:purchase_record_products)
    .where({ purchase_record_products: {created_at: Time.current.all_month} })
     PriceCalculator.total(sold_products)
  end

  def today_sales
    sold_products = self.products
    .joins(:purchase_record_products)
    .where({ purchase_record_products: {created_at: Time.current.all_day} })
     PriceCalculator.total(sold_products)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :basket_products, dependent: :destroy
  has_many :products, through: :basket_products

  def total_price(product_ids: nil)
    products = product_ids ? self.products.where(id: product_ids) : self.products
    PriceCalculator.total(products)
  end

end

app/models/basket_product.rb
class BasketProduct < ApplicationRecord
  belongs_to :basket
  belongs_to :product
end

app/models/charge.rb
class Charge 
  def initialize
     Stripe.api_key = ENV['STRIPE_SECRET_KEY']
  end

  def create!(price, token)
    Stripe::Charge.create({
      amount: price,
      currency: 'jpy',
      description: 'Example charge',
      source: token
    })
    end

    def self.create!(price, token)
      charge = self.new
      charge.create!(price, token)
    end
end

app/models/concerns/price_calculator.rb
module PriceCalculator
 def self.total(products)
  products.sum(:price)
 end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates_uniqueness_of :product_id, scope: :user_id
end

app/models/product.rb
class Product < ApplicationRecord
  include Hashid::Rails
  mount_uploader :image, ImageUploader
  has_many :basket_products, dependent: :destroy
  has_many :purchase_record_products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  belongs_to :admin
  
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image, presence: true
end

app/models/purchase_record.rb
class PurchaseRecord < ApplicationRecord
  belongs_to :user
  has_many :purchase_record_products, dependent: :destroy
  has_many :products, through: :purchase_record_products

end

app/models/purchase_record_product.rb
class PurchaseRecordProduct < ApplicationRecord
  belongs_to :product 
  belongs_to :purchase_record
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  
  has_one :basket, dependent: :destroy
  has_one :purchase_record, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_products, through: :favorites, source: :product
  
  
 

  def prepare_basket
    basket || create_basket
  end

 def prepare_purchase_record
   purchase_record || create_purchase_record
 end

def already_favorited?(product)
  self.favorites.exists?(product_id: product.id)
end


  def checkout!(token, product_ids:)
    total = basket.total_price(product_ids: product_ids)
    
    transaction do
      basket_products = basket.basket_products.where(product_id: product_ids)
      basket_products.each(&:destroy!)

      purchase_record = prepare_purchase_record
      ids = product_ids.map { |id| { product_id: id } }
      purchase_record.purchase_record_products.create!(ids)
    end

    Charge.create!(total, token)
  end

end

app/controllers/admins/application_controller.rb
class Admins::ApplicationController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admins/dashboards_controller.rb
class Admins::DashboardsController < Admins::ApplicationController
  def index
  end
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < Admins::ApplicationController
  
  def new 
    @product = current_admin.products.build
  end

  def create 
    @product = current_admin.products.build(product_params)
    if @product.save
      redirect_to admins_root_path, success: '商品を追加しました。'
    else
      flash[:error] = '追加に失敗しました。'
      render :new
    end
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      root_path
    else resource.is_a?(Admin)
      admins_root_path
    end
  end
  

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :authenticate_user!

  def show 
    basket = current_user.prepare_basket
    @products = basket.products
    @total_price = basket.products.sum(:price)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
     Stripe.api_key = ENV['STRIPE_SECRET_KEY']
   
    token = params[:stripeToken]
    product_ids = params[:product_ids].map(&:to_i)
    current_user.checkout!(token, product_ids: product_ids)
    redirect_to root_path, success: '決済に成功しました。'
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  
  def show 
   @favorite = current_user.favorite_products
  end

  def create 
   @product = Product.find(params[:product_id])
   @favorite = current_user.favorites.create(product_id: @product.id)
   redirect_back(fallback_location: root_path)
   
  end

  def destroy
    @product = Product.find(params[:product_id])
    @favorite = current_user.favorites.find_by(product_id: @product.id)
    @favorite.destroy
     redirect_back(fallback_location: root_path)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page])
  end

   def show 
    @product = Product.find(params[:id])
   end
  
    
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/dashboards/index.html.erb
<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>

<h1 class="mb-4">Dashboard</h1>

 <div class="row border rounded mb-2">
  <div class="col-md-5 mt-4">
    <h2>Total sales</h2>    
  </div>
  <div class="col-md-5 mt-4">
    <p class="h2"> <%= current_admin.total_sales.to_s(:delimited) %> 円</p>
   </div>
  <div class="col-md-2 mt-4">
    <%= link_to admins_sales_record_path do %>
      <p class="btn btn-dark">売上詳細<p>
    <% end %>
  </div>
 </div>


 <div class="row border rounded mb-2">
   <div class="col-md-5 mt-4">
    <h2>Sales of this month</h2> 
   </div>

   <div class="col-md-5 mt-4">
    <p class="h2"><%= current_admin.this_month_sales.to_s(:delimited) %> 円</p>
   </div>
   
   <div class="col-md-2 mt-4">
    <%= link_to admins_sales_record_path(start_at: Time.current.beginning_of_month, end_at: Time.current.end_of_month) do %>
      <p class="btn btn-dark">売上詳細<p>
    <% end %>
   </div>
  </div>


  <div class="row border rounded mb-2">
    <div class="col-md-5 mt-4">
      <h2>Today's sales</h2> 
    </div>

    <div class="col-md-5 mt-4">
    <p class="h2"><%= current_admin.today_sales.to_s(:delimited) %> 円</p>
   </div>

    <div class="col-md-2 mt-4">
      <%= link_to admins_sales_record_path(start_at: Time.current.beginning_of_day, end_at: Time.current.end_of_day) do %>
      <p class="btn btn-dark">売上詳細<p>
    <% end %>
    </div>
  </div>

<div class="row mb-2">
 <div class="col-md-11 mt-4 text-center">
  <%= link_to new_admins_product_path do %>
      <p class="btn btn-primary w-75">新しい商品を追加する</p>
  <% end %>
 </div>

 <div class="col-md-1 mt-4">
  <%= link_to destroy_admin_session_path, method: :delete do %>
    <p class="btn btn-secondary">Logout</p>
  <% end %>
 </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>